In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a + 2)
print(b**2)
print(a + b)
print(a**b)
print(a/b)
print(a-b)

[3 4 5 6]
[25 36 49 64]
[ 6  8 10 12]
[    1    64  2187 65536]
[0.2        0.33333333 0.42857143 0.5       ]
[-4 -4 -4 -4]


In [6]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8,9]) # addition can be possible with arrays of same size

print(a + b)

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [11]:
a.mean()

2.5

In [12]:
a.sum()

10

In [16]:
import math as m
d = ((a-b) ** 2).sum()
m.sqrt(d)

8.0

In [17]:
x = np.array([1,3,5,6])
((x - x.mean()) ** 2).sum() 

14.75

In [18]:
v1 = np.array([1,2,3])
v2 = np.array([4,-5,6])    # Dot Product

v1.dot(v2)

12