Numpy is a python library that supports large, multidimensional arrays and matrices along with a large collection of mathematical function to operate 
on these arrays

In [1]:
import numpy as np

In [2]:
li = [1,2,3,4]         # how to create numpy arrays
np.array(li)

array([1, 2, 3, 4])

In [7]:
a = np.zeroes(5)  # latest version of numpy does not support Zeroes 
print(a)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
a = np.ones((2,3),int)  # multidimensional array (2-D) (rows, columns) 1st row --> index 0; second row --> index 1
                        # if i want list of integer --> ((2,3),int)
print(a)

[[1 1 1]
 [1 1 1]]


In [34]:
b = np.ones((3,3,4), int) # (3-D, rows, columns) 1st row --> index 0; second row --> index 1; third row --> index 2
print(b)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [35]:
b.dtype    # to check datatypes

dtype('int32')

In [38]:
b[2] = 10   # Accessing elements 

In [39]:
b

array([[[ 2,  2,  2,  2],
        [ 2,  2,  2,  2],
        [ 2,  2,  2,  2]],

       [[ 1,  1,  1,  1],
        [ 1,  1,  1,  1],
        [ 1,  1,  1,  1]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [42]:
a[0][0]  # [row] [column]

1

In [57]:
b[2][2][2] = 38   # [index] [row] [column]

In [58]:
b

array([[[ 2,  2,  2,  2],
        [ 2,  2,  2,  2],
        [ 2,  2,  2,  2]],

       [[ 1,  1,  1,  1],
        [ 1,  1,  1,  1],
        [ 1,  1,  1,  1]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 38, 10]]])

In [61]:
a[0][2] = 13

In [62]:
a

array([[ 1,  1, 13],
       [ 1,  1,  1]])

In [66]:
a[0:1] # Slicing [index - (0); index - (n-1)]

array([[ 1,  1, 13]])

In [78]:
b[-1:]

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 38, 10]]])

In [68]:
b.shape # Size of numpy array using "Shape"

(3, 3, 4)

In [76]:
c = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [77]:
c[:, 1]  # [all rows :, column->1]

array([ 2,  5,  8, 11])

In [81]:
c[-2:]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [83]:
c[-2 : , 1]

array([ 8, 11])

In [88]:
c[:,2:3]    # sub-arrays

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [89]:
np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'